parameters:
  template.system: '@Websystems\BoilrCore\Service\PhpTemplate'

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Load Core services
  Websystems\BoilrCore\Service\:
    resource: '../src/Service'
    public: true

  # Load Core Controller
  Websystems\BoilrCore\Controller:
    abstract:  true
    calls:
      - setContainer: ['@service_container']

  Websystems\BoilrCore\Interfaces\TemplateInterface:
    public: true
    class: '%template.system%'

  # Add Event Subscriber services to Event Dispatcher
  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    public: true
    class: Symfony\Component\EventDispatcher\EventDispatcher

  Symfony\Component\HttpFoundation\Session\Session:
    public: true
    calls:
     - start: []

  Symfony\Component\HttpFoundation\Request:
    public: true
    factory: ['Symfony\Component\HttpFoundation\Request', 'createFromGlobals']
    calls:
      - setSession: ['@Symfony\Component\HttpFoundation\Session\Session']

  request:
    alias: Symfony\Component\HttpFoundation\Request
    public: true


